{
 "title": "AirCEP",
 "time": { "from": "2022-01-01T03:00:00.000Z", "to": "2022-01-15T01:56:17.704Z" },
 "panels": [
  {
   "title": "Gabriel de Souza Ribeiro",
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<h1 style=\"text-align:center;\">AirCEP</h1>"
   }
  },
  {
   "title": "MP10",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  CAST(timestamp AS DATETIME(3)) AS time,\n  CAST(particulasInalaveisMp10 AS UNSIGNED) AS metric\nFROM qualidade_ar\nWHERE timestamp BETWEEN $__timeFrom() AND $__timeTo()\nORDER BY timestamp"
    }
   ]
  },
  {
   "title": "MP2,5",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 5, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  CAST(timestamp AS DATETIME(3)) AS time,\n  CAST(particulasInalaveisFinasMp25 AS UNSIGNED) AS metric\nFROM qualidade_ar\nWHERE timestamp BETWEEN $__timeFrom() AND $__timeTo()\nORDER BY timestamp"
    }
   ]
  },
  {
   "title": "O3",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 10, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  CAST(timestamp AS DATETIME(3)) AS time,\n  CAST(ozonio AS UNSIGNED) AS metric\nFROM qualidade_ar\nWHERE timestamp BETWEEN $__timeFrom() AND $__timeTo()\nORDER BY timestamp"
    }
   ]
  },
  {
   "title": "CO",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 15, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  CAST(timestamp AS DATETIME(3)) AS time,\n  CAST(monoxidoDeCarbono AS UNSIGNED) AS metric\nFROM qualidade_ar\nWHERE timestamp BETWEEN $__timeFrom() AND $__timeTo()\nORDER BY timestamp"
    }
   ]
  },
  {
   "title": "NO2",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  CAST(timestamp AS DATETIME(3)) AS time,\n  CAST(dioxidoDeNitrogenio AS UNSIGNED) AS metric\nFROM qualidade_ar\nWHERE timestamp BETWEEN $__timeFrom() AND $__timeTo()\nORDER BY timestamp"
    }
   ]
  },
  {
   "title": "Último alerta",
   "type": "text",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 10 },
   "options": {
    "content": "<h1 style=\"text-align:center;\">MP10</h1>"
   }
  },
  {
   "title": "Último alerta",
   "type": "text",
   "gridPos": { "h": 3, "w": 5, "x": 5, "y": 10 },
   "options": {
    "content": "<h1 style=\"text-align:center;\">MP2,5</h1>"
   }
  },
  {
   "title": "Último alerta",
   "type": "text",
   "gridPos": { "h": 3, "w": 5, "x": 10, "y": 10 },
   "options": {
    "content": "<h1 style=\"text-align:center;\">O3</h1>"
   }
  },
  {
   "title": "Último alerta",
   "type": "text",
   "gridPos": { "h": 3, "w": 5, "x": 15, "y": 10 },
   "options": {
    "content": "<h1 style=\"text-align:center;\">CO</h1>"
   }
  },
  {
   "title": "Último alerta",
   "type": "text",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 10 },
   "options": {
    "content": "<h1 style=\"text-align:center;\">NO2</h1>"
   }
  },
  {
   "title": "MP10 - Alerta",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  CAST(timestamp AS DATETIME(3)) AS time,\n  CAST(particulasInalaveisMp10 AS UNSIGNED) AS metric\nFROM alertas_ar\nWHERE timestamp BETWEEN $__timeFrom() AND $__timeTo()\nORDER BY timestamp"
    }
   ]
  },
  {
   "title": "MP2,5 - Alerta",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 5, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  CAST(timestamp AS DATETIME(3)) AS time,\n  CAST(particulasInalaveisFinasMp25 AS UNSIGNED) AS metric\nFROM alertas_ar\nWHERE timestamp BETWEEN $__timeFrom() AND $__timeTo()\nORDER BY timestamp"
    }
   ]
  },
  {
   "title": "O3 - Alerta",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 10, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  CAST(timestamp AS DATETIME(3)) AS time,\n  CAST(ozonio AS UNSIGNED) AS metric\nFROM alertas_ar\nWHERE timestamp BETWEEN $__timeFrom() AND $__timeTo()\nORDER BY timestamp"
    }
   ]
  },
  {
   "title": "O2 - Alerta",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 15, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  CAST(timestamp AS DATETIME(3)) AS time,\n  CAST(monoxidoDeCarbono AS UNSIGNED) AS metric\nFROM alertas_ar\nWHERE timestamp BETWEEN $__timeFrom() AND $__timeTo()\nORDER BY timestamp"
    }
   ]
  },
  {
   "title": "NO2 - Alerta",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  CAST(timestamp AS DATETIME(3)) AS time,\n  CAST(dioxidoDeNitrogenio AS UNSIGNED) AS metric\nFROM alertas_ar\nWHERE timestamp BETWEEN $__timeFrom() AND $__timeTo()\nORDER BY timestamp"
    }
   ]
  },
  {
   "title": "MP10",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {
     "rawSql": "SELECT CAST(timestamp AS DATETIME(3)) AS time\n,\nCAST(particulasInalaveisMp10 AS UNSIGNED)\nFROM qualidade_ar\nWHERE timestamp BETWEEN $__timeFrom() AND $__timeTo()\nORDER BY time;"
    }
   ]
  },
  {
   "title": "MP2,5",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 28 },
   "targets": [
    {
     "rawSql": "SELECT CAST(timestamp AS DATETIME(3)) AS time\n,\nCAST(particulasInalaveisFinasMp25 AS UNSIGNED)\nFROM qualidade_ar\nWHERE timestamp BETWEEN $__timeFrom() AND $__timeTo()\nORDER BY time;"
    }
   ]
  },
  {
   "title": "O3",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 35 },
   "targets": [
    {
     "rawSql": "SELECT CAST(timestamp AS DATETIME(3)) AS time\n,\nCAST(ozonio AS UNSIGNED)\nFROM qualidade_ar\nWHERE timestamp BETWEEN $__timeFrom() AND $__timeTo()\nORDER BY time;"
    }
   ]
  },
  {
   "title": "CO",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 43 },
   "targets": [
    {
     "rawSql": "SELECT CAST(timestamp AS DATETIME(3)) AS time\n,\nCAST(monoxidoDeCarbono AS UNSIGNED)\nFROM qualidade_ar\nWHERE timestamp BETWEEN $__timeFrom() AND $__timeTo()\nORDER BY time;"
    }
   ]
  },
  {
   "title": "NO2",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 50 },
   "targets": [
    {
     "rawSql": "SELECT CAST(timestamp AS DATETIME(3)) AS time\n,\nCAST(dioxidoDeNitrogenio AS UNSIGNED)\nFROM qualidade_ar\nWHERE timestamp BETWEEN $__timeFrom() AND $__timeTo()\nORDER BY time;"
    }
   ]
  }
 ]
}